In [7]:
import numpy as np
print(np.__version__)

1.21.5


In [24]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a)
print(type(a))#type of 
print(a.shape) # shape
print(a.size) # size
print(a.nbytes) #memory allocated
print(a.ndim) #dimension
print(a.dtype)


[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(9,)
9
9
1
int8


In [22]:
print(a.nbytes) #memory allocated
print(a.ndim) #dimension
print(a.dtype)

18
1
int16


In [25]:
x = [1, 2, 3, 4, 5, 6] #regular lists
y = [7, 8, 9, 10, 11, 12]
print(x + y)


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]


In [27]:
x = np.array([1, 2, 3, 4, 5, 6])
y = np.array([7, 8, 9, 10, 11, 12])
print(x + y)
print(x - y)
print(x * y)

[ 8 10 12 14 16 18]
[-6 -6 -6 -6 -6 -6]
[ 7 16 27 40 55 72]
