In [3]:
import numpy as np
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print(f"{a} \n{b}")

[1 2 3 4] 
[5 6 7 8]


In [4]:
c = a + b
print(c)

[ 6  8 10 12]


In [5]:
print(type(c))

<class 'numpy.ndarray'>


In [6]:
print(c.size)

4


In [8]:
print(c.shape)

(4,)


In [9]:
print(c.sum())

36


# these are practice sets


In [10]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(x)

[1 2 3 4 5 6 7 8 9]


In [11]:
print(x.sum())

45


In [12]:
print(x.min())

1


In [13]:
print(x.max())

9


In [14]:
print(x.mean())

5.0


In [15]:
print(x.std())

2.581988897471611


In [16]:
print(x[2])

3


In [17]:
print(x[1:5])

[2 3 4 5]


In [18]:
x[1:5]

array([2, 3, 4, 5])

In [19]:
print(x)

[1 2 3 4 5 6 7 8 9]


In [20]:
x =x* a[1]

In [21]:
print(x)

[ 5 10 15 20 25 30 35 40 45]


In [22]:
c = np.array([5, 6, 7])
d = np.array([9, 10, 11])


In [23]:
c[1]

6

In [24]:
print(d*c[1])

[54 60 66]


In [25]:
print(x)

[ 5 10 15 20 25 30 35 40 45]


In [26]:
x = np.array([1, 2, 3, 4, 5, 6])
print(x)

[1 2 3 4 5 6]


In [27]:
x = x.reshape(2,3)

In [28]:
print(x)

[[1 2 3]
 [4 5 6]]


In [29]:
x

array([[1, 2, 3],
       [4, 5, 6]])