In [5]:
import numpy as np
print(np.__version__)

1.21.5


In [6]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)

[1 2 3 4 5 6]


In [7]:
b = np.array([[1, 2, 3],[4, 5, 6]])
print(b)


[[1 2 3]
 [4 5 6]]


In [9]:
print(b.shape)
print(b.size)

(2, 3)
6


In [10]:
x = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [12]:
print(x.shape)
print(x.size)

(3, 3)
9


In [14]:
print(x[2][2])
print(x[1][2])

9
6


In [17]:
print(x.sum())
print(x.sum(axis=0))
print(x.sum(axis=1))

45
[12 15 18]
[ 6 15 24]


In [18]:
a = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
print(a[0,:]) #accessing particular row

[1 2 3]


In [21]:
print(a[1,:]) 

[4 5 6]


In [22]:
print(a[:,0]) #accessing particular column

[1 4 7]


In [23]:
print(a[:,2])

[3 6 9]


In [24]:
x = np.arange(15)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
x = np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [26]:
x = np.ones(5)
print(x)

[1. 1. 1. 1. 1.]


In [27]:
x = np.full([2,3],9)

In [28]:
print(x)

[[9 9 9]
 [9 9 9]]


In [34]:
x = np.identity(5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [36]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
b = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18])
print(a)
print(b)

[1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18]


In [41]:
c = np.hstack([a,b])
print(c)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [42]:
c = np.vstack([a,b])
print(c)

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]]


In [38]:
print(a[1:7:2])

[2 4 6]


In [39]:
print(a[::])

[1 2 3 4 5 6 7 8 9]


In [64]:
a = np.genfromtxt('data.txt', delimiter = '',dtype=None,encoding=None)
print(a)

['1,2,3,4,5' '6,7,8,9,10' '11,12,13,14,15']
